image: java:17-jdk
stages:
  - test
  - build
before_script:
  - chmod +x mvnw
test:
  state: test
  script: ./mvnw test
build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/microservice-basic-0.0.1-SNAPSHOT.jar
after_script:
  - echo “End CI”