image: openjdk:17-alpine

before_script:
  - apk update && apk add git
  - git --version

stages:
  - build
  - test
  - deploy

build:
  image: maven:latest
  stage: build
  script:
    - mvn clean package -Pdev

test:
  image: maven:latest
  stage: test
  script:
    - mvn test -B

deploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/microservice-simple-example.git
    - git push -f heroku HEAD:refs/main
  environment:
    name: staging
    url: https://microservice-simple-example.herokuapp.com