image: java:17-jdk
cache:
  paths:
    - .m2/repository
stages:
  - build
before_script:
  - chmod +x mvnw
build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/BackEnd-Project-0.0.1-SNAPSHOT.jar
after_script:
  - echo “End CI”